openapi: 3.1.0
info:
  title: Box Authorize API
paths:
  /authorize:
    get:
      summary: Authorize user
      description: |-
        Authorize a user by sending them through the [Box](https://box.com)
        website and request their permission to act on their behalf.

        This is the first step when authenticating a user using
        OAuth 2.0. To request a user's authorization to use the Box APIs
        on their behalf you will need to send a user to the URL with this
        format.
      tags:
        - Authorize
        - User
        - Authori
