openapi: 3.1.0
info:
  title: Box Collaboration Whitelist Entries API
  description: Needs a description.
paths:
  /collaboration_whitelist_entries:
    get:
      operationId: get_collaboration_whitelist_entries
      summary: List allowed collaboration domains
      tags:
        - - - - Domain restrictions for collaborations
      x-box-tag: collaboration_allowlist_entries
      description: >-
        Returns the list domains that have been deemed safe to create
        collaborations

        for within the current enterprise.
      parameters:
        - name: marker
          description: >-
            Defines the position marker at which to begin returning results.
            This is

            used when paginating using marker-based pagination.


            This requires `usemarker` to be set to `true`.
          in: query
          required: false
          example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVii
          schema:
            type: string
        - name: limit
          description: The maximum number of items to return per page.
          in: query
          required: false
          example: 1000
          schema:
            type: integer
            format: int64
            maximum: 1000
      responses:
        '200':
          description: Returns a collection of domains that are allowed for collaboration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollaborationAllowlistEntries'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    post:
      operationId: post_collaboration_whitelist_entries
      summary: Add domain to list of allowed collaboration domains
      tags:
        - - - - Domain restrictions for collaborations
      x-box-tag: collaboration_allowlist_entries
      description: |-
        Creates a new entry in the list of allowed domains to allow
        collaboration for.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - domain
                - direction
              properties:
                domain:
                  type: string
                  description: The domain to add to the list of allowed domains.
                  example: example.com
                direction:
                  type: string
                  description: The direction in which to allow collaborations.
                  example: inbound
                  enum:
                    - inbound
                    - outbound
                    - both
      responses:
        '200':
          description: Returns a new entry on the list of allowed domains.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollaborationAllowlistEntry'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
  /collaboration_whitelist_entries/{collaboration_whitelist_entry_id}:
    get:
      operationId: get_collaboration_whitelist_entries_id
      summary: Get allowed collaboration domain
      tags:
        - - - - Domain restrictions for collaborations
      x-box-tag: collaboration_allowlist_entries
      description: |-
        Returns a domain that has been deemed safe to create collaborations
        for within the current enterprise.
      parameters:
        - name: collaboration_whitelist_entry_id
          description: The ID of the entry in the list.
          in: path
          required: true
          example: '213123'
          schema:
            type: string
      responses:
        '200':
          description: Returns an entry on the list of allowed domains.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollaborationAllowlistEntry'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    delete:
      operationId: delete_collaboration_whitelist_entries_id
      summary: Remove domain from list of allowed collaboration domains
      tags:
        - - - - Domain restrictions for collaborations
      x-box-tag: collaboration_allowlist_entries
      description: >-
        Removes a domain from the list of domains that have been deemed safe to
        create

        collaborations for within the current enterprise.
      parameters:
        - name: collaboration_whitelist_entry_id
          description: The ID of the entry in the list.
          in: path
          required: true
          example: '213123'
          schema:
            type: string
      responses:
        '204':
          description: |-
            A blank response is returned if the entry was
            successfully deleted.
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
components:
  schemas:
    CollaborationAllowlistEntries:
      title: Allowed collaboration domains
      type: object
      x-box-resource-id: collaboration_allowlist_entries
      x-box-tag: collaboration_allowlist_entries
      description: A list of allowed domains for collaboration.
      allOf:
        - type: object
          description: |-
            The part of an API response that describes marker
            based pagination
          properties:
            limit:
              description: >-
                The limit that was used for these entries. This will be the same
                as the

                `limit` query parameter unless that value exceeded the maximum
                value

                allowed. The maximum value varies by API.
              example: 1000
              type: integer
              format: int64
            next_marker:
              description: The marker for the start of the next page of results.
              example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVii
              type: string
              nullable: true
            prev_marker:
              description: The marker for the start of the previous page of results.
              example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVih
              type: string
              nullable: true
        - properties:
            entries:
              type: array
              description: A list of allowed collaboration domains
              items:
                $ref: '#/components/schemas/CollaborationAllowlistEntry'
    ClientError:
      title: Client error
      type: object
      x-box-resource-id: client_error
      description: A generic error
      properties:
        type:
          description: error
          example: error
          type: string
          enum:
            - error
          nullable: false
        status:
          description: The HTTP status of the response.
          example: 400
          type: integer
          format: int32
          nullable: false
        code:
          description: A Box-specific error code
          example: item_name_invalid
          type: string
          enum:
            - created
            - accepted
            - no_content
            - redirect
            - not_modified
            - bad_request
            - unauthorized
            - forbidden
            - not_found
            - method_not_allowed
            - conflict
            - precondition_failed
            - too_many_requests
            - internal_server_error
            - unavailable
            - item_name_invalid
            - insufficient_scope
        message:
          description: A short message describing the error.
          example: Method Not Allowed
          type: string
          nullable: false
        context_info:
          description: |-
            A free-form object that contains additional context
            about the error. The possible fields are defined on
            a per-endpoint basis. `message` is only one example.
          type: object
          nullable: true
          properties:
            message:
              type: string
              description: More details on the error.
              example: Something went wrong.
        help_url:
          description: A URL that links to more information about why this error occurred.
          example: >-
            https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/
          type: string
          nullable: false
        request_id:
          description: |-
            A unique identifier for this response, which can be used
            when contacting Box support.
          type: string
          example: abcdef123456
          nullable: false
    CollaborationAllowlistEntry:
      title: Allowed collaboration domain
      type: object
      x-box-resource-id: collaboration_allowlist_entry
      x-box-tag: collaboration_allowlist_entries
      description: >-
        An entry that describes an approved domain for which users can
        collaborate

        with files and folders in your enterprise or vice versa.
      properties:
        id:
          type: string
          description: The unique identifier for this entry
          example: '11446498'
        type:
          type: string
          description: '`collaboration_whitelist_entry`'
          example: collaboration_whitelist_entry
          enum:
            - collaboration_whitelist_entry
        domain:
          type: string
          example: example.com
          description: The whitelisted domain
        direction:
          type: string
          example: both
          description: The direction of the collaborations to allow.
          enum:
            - inbound
            - outbound
            - both
        enterprise:
          allOf:
            - title: Enterprise
              type: object
              description: A representation of a Box enterprise
              properties:
                id:
                  type: string
                  description: The unique identifier for this enterprise.
                  example: '11446498'
                type:
                  type: string
                  description: '`enterprise`'
                  example: enterprise
                  enum:
                    - enterprise
                name:
                  description: The name of the enterprise
                  example: Acme Inc.
                  type: string
            - description: The enterprise this list is applied to
        created_at:
          type: string
          format: date-time
          description: The time the entry was created at
          example: '2012-12-12T10:53:43-08:00'
tags: []
