openapi: 3.1.0
info:
  title: Box Storage Policy Assignments API
  description: Needs a description.
paths:
  /storage_policy_assignments:
    get:
      operationId: get_storage_policy_assignments
      summary: List storage policy assignments
      tags:
        - - - - Standard and Zones Storage Policy Assignments
      x-box-tag: storage_policy_assignments
      description: Fetches all the storage policy assignment for an enterprise or user.
      parameters:
        - name: marker
          description: >-
            Defines the position marker at which to begin returning results.
            This is

            used when paginating using marker-based pagination.


            This requires `usemarker` to be set to `true`.
          in: query
          required: false
          example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVii
          schema:
            type: string
        - name: resolved_for_type
          in: query
          example: user
          description: The target type to return assignments for
          required: true
          schema:
            type: string
            enum:
              - user
              - enterprise
        - name: resolved_for_id
          in: query
          required: true
          example: '984322'
          description: The ID of the user or enterprise to return assignments for
          schema:
            type: string
      responses:
        '200':
          description: |-
            Returns a collection of storage policies for
            the enterprise or user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoragePolicyAssignments'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    post:
      operationId: post_storage_policy_assignments
      summary: Assign storage policy
      tags:
        - - - - Standard and Zones Storage Policy Assignments
      x-box-tag: storage_policy_assignments
      description: Creates a storage policy assignment for an enterprise or user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - storage_policy
                - assigned_to
              properties:
                storage_policy:
                  type: object
                  description: |-
                    The storage policy to assign to the user or
                    enterprise
                  required:
                    - type
                    - id
                  properties:
                    type:
                      type: string
                      description: The type to assign.
                      example: storage_policy
                      enum:
                        - storage_policy
                    id:
                      type: string
                      description: The ID of the storage policy to assign.
                      example: '1434325'
                assigned_to:
                  type: object
                  description: |-
                    The user or enterprise to assign the storage
                    policy to.
                  required:
                    - type
                    - id
                  properties:
                    type:
                      type: string
                      description: The type to assign the policy to.
                      example: user
                      enum:
                        - user
                        - enterprise
                    id:
                      type: string
                      description: The ID of the user or enterprise
                      example: '9987987'
      responses:
        '200':
          description: Returns the new storage policy assignment created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoragePolicyAssignment'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
  /storage_policy_assignments/{storage_policy_assignment_id}:
    get:
      operationId: get_storage_policy_assignments_id
      summary: Get storage policy assignment
      tags:
        - - - - Standard and Zones Storage Policy Assignments
      x-box-tag: storage_policy_assignments
      description: Fetches a specific storage policy assignment.
      parameters:
        - name: storage_policy_assignment_id
          description: The ID of the storage policy assignment.
          example: '932483'
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns a storage policy assignment object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoragePolicyAssignment'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    put:
      operationId: put_storage_policy_assignments_id
      summary: Update storage policy assignment
      tags:
        - - - - Standard and Zones Storage Policy Assignments
      x-box-tag: storage_policy_assignments
      description: Updates a specific storage policy assignment.
      parameters:
        - name: storage_policy_assignment_id
          description: The ID of the storage policy assignment.
          example: '932483'
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - storage_policy
              properties:
                storage_policy:
                  type: object
                  description: |-
                    The storage policy to assign to the user or
                    enterprise
                  required:
                    - type
                    - id
                  properties:
                    type:
                      type: string
                      description: The type to assign.
                      example: storage_policy
                      enum:
                        - storage_policy
                    id:
                      type: string
                      description: The ID of the storage policy to assign.
                      example: '1434325'
      responses:
        '200':
          description: Returns an updated storage policy assignment object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoragePolicyAssignment'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    delete:
      operationId: delete_storage_policy_assignments_id
      summary: Unassign storage policy
      tags:
        - - - - Standard and Zones Storage Policy Assignments
      x-box-tag: storage_policy_assignments
      description: |-
        Delete a storage policy assignment.

        Deleting a storage policy assignment on a user
        will have the user inherit the enterprise's default
        storage policy.

        There is a rate limit for calling this endpoint of only
        twice per user in a 24 hour time frame.
      parameters:
        - name: storage_policy_assignment_id
          description: The ID of the storage policy assignment.
          example: '932483'
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: |-
            Returns an empty response when the storage policy
            assignment is successfully deleted.
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
components:
  schemas:
    StoragePolicyAssignments:
      title: Storage policy assignments
      type: object
      x-box-resource-id: storage_policy_assignments
      x-box-tag: storage_policy_assignments
      description: A list of storage policy assignments.
      allOf:
        - type: object
          description: |-
            The part of an API response that describes marker
            based pagination
          properties:
            limit:
              description: >-
                The limit that was used for these entries. This will be the same
                as the

                `limit` query parameter unless that value exceeded the maximum
                value

                allowed. The maximum value varies by API.
              example: 1000
              type: integer
              format: int64
            next_marker:
              description: The marker for the start of the next page of results.
              example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVii
              type: string
              nullable: true
            prev_marker:
              description: The marker for the start of the previous page of results.
              example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVih
              type: string
              nullable: true
        - properties:
            entries:
              type: array
              description: A list of storage policy assignments
              items:
                $ref: '#/components/schemas/StoragePolicyAssignment'
    ClientError:
      title: Client error
      type: object
      x-box-resource-id: client_error
      description: A generic error
      properties:
        type:
          description: error
          example: error
          type: string
          enum:
            - error
          nullable: false
        status:
          description: The HTTP status of the response.
          example: 400
          type: integer
          format: int32
          nullable: false
        code:
          description: A Box-specific error code
          example: item_name_invalid
          type: string
          enum:
            - created
            - accepted
            - no_content
            - redirect
            - not_modified
            - bad_request
            - unauthorized
            - forbidden
            - not_found
            - method_not_allowed
            - conflict
            - precondition_failed
            - too_many_requests
            - internal_server_error
            - unavailable
            - item_name_invalid
            - insufficient_scope
        message:
          description: A short message describing the error.
          example: Method Not Allowed
          type: string
          nullable: false
        context_info:
          description: |-
            A free-form object that contains additional context
            about the error. The possible fields are defined on
            a per-endpoint basis. `message` is only one example.
          type: object
          nullable: true
          properties:
            message:
              type: string
              description: More details on the error.
              example: Something went wrong.
        help_url:
          description: A URL that links to more information about why this error occurred.
          example: >-
            https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/
          type: string
          nullable: false
        request_id:
          description: |-
            A unique identifier for this response, which can be used
            when contacting Box support.
          type: string
          example: abcdef123456
          nullable: false
    StoragePolicyAssignment:
      title: Storage policy assignment
      type: object
      x-box-resource-id: storage_policy_assignment
      x-box-tag: storage_policy_assignments
      description: The assignment of a storage policy to a user or enterprise
      required:
        - id
        - type
      properties:
        id:
          type: string
          description: The unique identifier for a storage policy assignment.
          example: ZW50ZXJwcmlzZV8xMjM0NTY3ODkw
        type:
          type: string
          description: '`storage_policy_assignment`'
          example: storage_policy_assignment
          enum:
            - storage_policy_assignment
        storage_policy:
          allOf:
            - $ref: '#/components/schemas/StoragePolicy--Mini'
            - description: The assigned storage policy
        assigned_to:
          allOf:
            - title: Reference
              description: The bare basic reference for an object
              type: object
              properties:
                id:
                  type: string
                  description: The unique identifier for this object
                  example: '11446498'
                type:
                  type: string
                  description: The type for this object
                  example: file
            - description: The enterprise or use the policy is assigned to
tags: []
