openapi: 3.1.0
info:
  title: Box Collaboration Whitelist Exempt Targets API
  description: Needs a description.
paths:
  /collaboration_whitelist_exempt_targets:
    get:
      operationId: get_collaboration_whitelist_exempt_targets
      summary: List users exempt from collaboration domain restrictions
      tags:
        - - - - Domain restrictions (User exemptions)
      x-box-tag: collaboration_allowlist_exempt_targets
      description: |-
        Returns a list of users who have been exempt from the collaboration
        domain restrictions.
      parameters:
        - name: marker
          description: >-
            Defines the position marker at which to begin returning results.
            This is

            used when paginating using marker-based pagination.


            This requires `usemarker` to be set to `true`.
          in: query
          required: false
          example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVii
          schema:
            type: string
        - name: limit
          description: The maximum number of items to return per page.
          in: query
          required: false
          example: 1000
          schema:
            type: integer
            format: int64
            maximum: 1000
      responses:
        '200':
          description: Returns a collection of user exemptions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollaborationAllowlistExemptTargets'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    post:
      operationId: post_collaboration_whitelist_exempt_targets
      summary: Create user exemption from collaboration domain restrictions
      tags:
        - - - - Domain restrictions (User exemptions)
      x-box-tag: collaboration_allowlist_exempt_targets
      description: >-
        Exempts a user from the restrictions set out by the allowed list of
        domains

        for collaborations.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - user
              properties:
                user:
                  type: object
                  description: The user to exempt.
                  required:
                    - id
                  properties:
                    id:
                      type: string
                      description: The ID of the user to exempt.
                      example: '23522323'
      responses:
        '200':
          description: Returns a new exemption entry.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollaborationAllowlistExemptTarget'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
  /collaboration_whitelist_exempt_targets/{collaboration_whitelist_exempt_target_id}:
    get:
      operationId: get_collaboration_whitelist_exempt_targets_id
      summary: Get user exempt from collaboration domain restrictions
      tags:
        - - - - Domain restrictions (User exemptions)
      x-box-tag: collaboration_allowlist_exempt_targets
      description: |-
        Returns a users who has been exempt from the collaboration
        domain restrictions.
      parameters:
        - name: collaboration_whitelist_exempt_target_id
          description: The ID of the exemption to the list.
          in: path
          required: true
          example: '984923'
          schema:
            type: string
      responses:
        '200':
          description: Returns the user's exempted from the list of collaboration domains.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollaborationAllowlistExemptTarget'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    delete:
      operationId: delete_collaboration_whitelist_exempt_targets_id
      summary: Remove user from list of users exempt from domain restrictions
      tags:
        - - - - Domain restrictions (User exemptions)
      x-box-tag: collaboration_allowlist_exempt_targets
      description: >-
        Removes a user's exemption from the restrictions set out by the allowed
        list

        of domains for collaborations.
      parameters:
        - name: collaboration_whitelist_exempt_target_id
          description: The ID of the exemption to the list.
          in: path
          required: true
          example: '984923'
          schema:
            type: string
      responses:
        '204':
          description: |-
            A blank response is returned if the exemption was
            successfully deleted.
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
components:
  schemas:
    CollaborationAllowlistExemptTargets:
      title: Allowed collaboration domains user exemptions
      type: object
      x-box-resource-id: collaboration_allowlist_exempt_targets
      x-box-tag: collaboration_allowlist_exempt_targets
      description: >-
        A list of users exempt from any of the restrictions

        imposed by the list of allowed collaboration domains for this
        enterprise.
      allOf:
        - type: object
          description: |-
            The part of an API response that describes marker
            based pagination
          properties:
            limit:
              description: >-
                The limit that was used for these entries. This will be the same
                as the

                `limit` query parameter unless that value exceeded the maximum
                value

                allowed. The maximum value varies by API.
              example: 1000
              type: integer
              format: int64
            next_marker:
              description: The marker for the start of the next page of results.
              example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVii
              type: string
              nullable: true
            prev_marker:
              description: The marker for the start of the previous page of results.
              example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVih
              type: string
              nullable: true
        - properties:
            entries:
              type: array
              description: |-
                A list of users exempt from any of the restrictions
                imposed by the list of allowed collaboration domains
                for this enterprise.
              items:
                $ref: '#/components/schemas/CollaborationAllowlistExemptTarget'
    ClientError:
      title: Client error
      type: object
      x-box-resource-id: client_error
      description: A generic error
      properties:
        type:
          description: error
          example: error
          type: string
          enum:
            - error
          nullable: false
        status:
          description: The HTTP status of the response.
          example: 400
          type: integer
          format: int32
          nullable: false
        code:
          description: A Box-specific error code
          example: item_name_invalid
          type: string
          enum:
            - created
            - accepted
            - no_content
            - redirect
            - not_modified
            - bad_request
            - unauthorized
            - forbidden
            - not_found
            - method_not_allowed
            - conflict
            - precondition_failed
            - too_many_requests
            - internal_server_error
            - unavailable
            - item_name_invalid
            - insufficient_scope
        message:
          description: A short message describing the error.
          example: Method Not Allowed
          type: string
          nullable: false
        context_info:
          description: |-
            A free-form object that contains additional context
            about the error. The possible fields are defined on
            a per-endpoint basis. `message` is only one example.
          type: object
          nullable: true
          properties:
            message:
              type: string
              description: More details on the error.
              example: Something went wrong.
        help_url:
          description: A URL that links to more information about why this error occurred.
          example: >-
            https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/
          type: string
          nullable: false
        request_id:
          description: |-
            A unique identifier for this response, which can be used
            when contacting Box support.
          type: string
          example: abcdef123456
          nullable: false
    CollaborationAllowlistExemptTarget:
      title: Allowed collaboration domains user exemption
      type: object
      x-box-resource-id: collaboration_allowlist_exempt_target
      x-box-tag: collaboration_allowlist_exempt_targets
      description: >-
        The user that is exempt from any of the restrictions

        imposed by the list of allowed collaboration domains for this
        enterprise.
      properties:
        id:
          type: string
          description: The unique identifier for this exemption
          example: '11446498'
        type:
          type: string
          description: '`collaboration_whitelist_exempt_target`'
          example: collaboration_whitelist_exempt_target
          enum:
            - collaboration_whitelist_exempt_target
        enterprise:
          allOf:
            - title: Enterprise
              type: object
              description: A representation of a Box enterprise
              properties:
                id:
                  type: string
                  description: The unique identifier for this enterprise.
                  example: '11446498'
                type:
                  type: string
                  description: '`enterprise`'
                  example: enterprise
                  enum:
                    - enterprise
                name:
                  description: The name of the enterprise
                  example: Acme Inc.
                  type: string
            - description: The enterprise this entry belongs to
        user:
          allOf:
            - $ref: '#/components/schemas/User--Mini'
            - description: The user that has been exempt
        created_at:
          type: string
          format: date-time
          description: The time the entry was created
          example: '2012-12-12T10:53:43-08:00'
        modified_at:
          type: string
          format: date-time
          description: The time the entry was modified
          example: '2012-12-12T10:53:43-08:00'
tags: []
