openapi: 3.1.0
info:
  title: Box Shield Information Barriers API
  description: Needs a description.
paths:
  /shield_information_barriers/{shield_information_barrier_id}:
    get:
      operationId: get_shield_information_barriers_id
      summary: Get shield information barrier with specified ID
      tags:
        - - - - Shield information barriers
      x-box-tag: shield_information_barriers
      description: Get shield information barrier based on provided ID.
      parameters:
        - name: shield_information_barrier_id
          description: The ID of the shield information barrier.
          example: '1910967'
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns the shield information barrier object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShieldInformationBarrier'
        '404':
          description: |-
            Returns a `not_found` error if
            the shield information barrier was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
  /shield_information_barriers/change_status:
    post:
      operationId: post_shield_information_barriers_change_status
      summary: Add changed status of shield information barrier with specified ID
      tags:
        - - - - Shield information barriers
      x-box-tag: shield_information_barriers
      description: Change status of shield information barrier with the specified ID.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - status
              properties:
                id:
                  type: string
                  example: '1910967'
                  description: The ID of the shield information barrier.
                status:
                  type: string
                  enum:
                    - pending
                    - disabled
                  example: pending
                  description: The desired status for the shield information barrier.
      responses:
        '200':
          description: Returns the updated shield information barrier object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShieldInformationBarrier'
        '404':
          description: |-
            Returns a `not_found` error if the
            shield information barrier was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '409':
          description: |-
            Returns an error if there exists Conflicts
            with existing information barriers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
  /shield_information_barriers:
    get:
      operationId: get_shield_information_barriers
      summary: List shield information barriers
      tags:
        - - - - Shield information barriers
      x-box-tag: shield_information_barriers
      description: |-
        Retrieves a list of shield information barrier objects
        for the enterprise of JWT.
      parameters:
        - name: marker
          description: >-
            Defines the position marker at which to begin returning results.
            This is

            used when paginating using marker-based pagination.
          in: query
          required: false
          example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVii
          schema:
            type: string
        - name: limit
          description: The maximum number of items to return per page.
          in: query
          required: false
          example: 1000
          schema:
            type: integer
            format: int64
            maximum: 1000
      responses:
        '200':
          description: |-
            Returns a paginated list of
            shield information barrier objects,
            empty list if currently no barrier.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShieldInformationBarriers'
        '404':
          description: >-
            Returns a `not_found` error if could not find an enterprise using
            JWT.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    post:
      operationId: post_shield_information_barriers
      summary: Create shield information barrier
      tags:
        - - - - Shield information barriers
      x-box-tag: shield_information_barriers
      description: |-
        Creates a shield information barrier to
        separate individuals/groups within the same
        firm and prevents confidential information passing between them.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                enterprise:
                  allOf:
                    - $ref: '#/components/schemas/Enterprise--Base'
                  description: The `type` and `id` of enterprise this barrier is under.
              required:
                - enterprise
      responses:
        '201':
          description: Returns a new shield information barrier object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShieldInformationBarrier'
        '404':
          description: Returns an error if the enterprise was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
components:
  schemas:
    ShieldInformationBarrier:
      title: Shield information barrier
      type: object
      x-box-resource-id: shield_information_barrier
      x-box-tag: shield_information_barriers
      x-box-variants:
        - base
        - standard
      x-box-variant: standard
      description: |-
        A standard representation of a
        shield information barrier object
      properties:
        id:
          type: string
          example: '11446498'
          description: The unique identifier for the shield information barrier
        type:
          type: string
          description: The type of the shield information barrier
          example: shield_information_barrier
          enum:
            - shield_information_barrier
        enterprise:
          allOf:
            - $ref: '#/components/schemas/Enterprise--Base'
          description: The `type` and `id` of enterprise this barrier is under.
        status:
          type: string
          enum:
            - draft
            - pending
            - disabled
            - enabled
            - invalid
          description: Status of the shield information barrier
          example: draft
        created_at:
          type: string
          format: date-time
          example: '2020-06-26T18:44:45.869Z'
          description: |-
            ISO date time string when this
            shield information barrier object was created.
        created_by:
          allOf:
            - $ref: '#/components/schemas/User--Base'
          description: The user who created this shield information barrier.
        updated_at:
          type: string
          format: date-time
          example: '2020-07-26T18:44:45.869Z'
          description: >-
            ISO date time string when this shield information barrier was
            updated.
        updated_by:
          allOf:
            - $ref: '#/components/schemas/User--Base'
          description: The user that updated this shield information barrier.
        enabled_at:
          type: string
          format: date-time
          example: '2020-07-26T18:44:45.869Z'
          description: >-
            ISO date time string when this shield information barrier was
            enabled.
        enabled_by:
          allOf:
            - $ref: '#/components/schemas/User--Base'
            - description: The user that enabled this shield information barrier.
    ClientError:
      title: Client error
      type: object
      x-box-resource-id: client_error
      description: A generic error
      properties:
        type:
          description: error
          example: error
          type: string
          enum:
            - error
          nullable: false
        status:
          description: The HTTP status of the response.
          example: 400
          type: integer
          format: int32
          nullable: false
        code:
          description: A Box-specific error code
          example: item_name_invalid
          type: string
          enum:
            - created
            - accepted
            - no_content
            - redirect
            - not_modified
            - bad_request
            - unauthorized
            - forbidden
            - not_found
            - method_not_allowed
            - conflict
            - precondition_failed
            - too_many_requests
            - internal_server_error
            - unavailable
            - item_name_invalid
            - insufficient_scope
        message:
          description: A short message describing the error.
          example: Method Not Allowed
          type: string
          nullable: false
        context_info:
          description: |-
            A free-form object that contains additional context
            about the error. The possible fields are defined on
            a per-endpoint basis. `message` is only one example.
          type: object
          nullable: true
          properties:
            message:
              type: string
              description: More details on the error.
              example: Something went wrong.
        help_url:
          description: A URL that links to more information about why this error occurred.
          example: >-
            https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/
          type: string
          nullable: false
        request_id:
          description: |-
            A unique identifier for this response, which can be used
            when contacting Box support.
          type: string
          example: abcdef123456
          nullable: false
    ShieldInformationBarriers:
      title: List of Shield Information Barriers
      type: object
      x-box-resource-id: shield_information_barriers
      x-box-tag: shield_information_barriers
      description: List of Shield Information Barrier objects
      allOf:
        - type: object
          description: |-
            The part of an API response that describes marker
            based pagination
          properties:
            limit:
              description: >-
                The limit that was used for these entries. This will be the same
                as the

                `limit` query parameter unless that value exceeded the maximum
                value

                allowed. The maximum value varies by API.
              example: 1000
              type: integer
              format: int64
            next_marker:
              description: The marker for the start of the next page of results.
              example: JV9IRGZmieiBasejOG9yDCRNgd2ymoZIbjsxbJMjIs3kioVii
              type: string
              nullable: true
        - properties:
            entries:
              type: array
              description: A list of shield information barrier objects
              items:
                $ref: '#/components/schemas/ShieldInformationBarrier'
tags: []
