openapi: 3.1.0
info:
  title: Box Terms Of Service User Statuses API
  description: Needs a description.
paths:
  /terms_of_service_user_statuses:
    get:
      operationId: get_terms_of_service_user_statuses
      summary: List terms of service user statuses
      tags:
        - - - - Terms of service user statuses
      x-box-tag: terms_of_service_user_statuses
      description: |-
        Retrieves an overview of users and their status for a
        terms of service, including Whether they have accepted
        the terms and when.
      parameters:
        - name: tos_id
          description: The ID of the terms of service.
          example: '324234'
          in: query
          required: true
          schema:
            type: string
        - name: user_id
          description: Limits results to the given user ID.
          example: '123334'
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Returns a list of terms of service statuses.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TermsOfServiceUserStatuses'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
    post:
      operationId: post_terms_of_service_user_statuses
      summary: Create terms of service status for new user
      tags:
        - - - - Terms of service user statuses
      x-box-tag: terms_of_service_user_statuses
      description: Sets the status for a terms of service for a user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - tos
                - user
                - is_accepted
              properties:
                tos:
                  type: object
                  description: The terms of service to set the status for.
                  required:
                    - id
                    - type
                  properties:
                    type:
                      type: string
                      description: The type of object.
                      example: terms_of_service
                      enum:
                        - terms_of_service
                    id:
                      type: string
                      description: The ID of terms of service
                      example: '1232132'
                user:
                  type: object
                  description: The user to set the status for.
                  required:
                    - id
                    - type
                  properties:
                    type:
                      type: string
                      description: The type of object.
                      example: user
                      enum:
                        - user
                    id:
                      type: string
                      description: The ID of user
                      example: '3423423'
                is_accepted:
                  type: boolean
                  example: true
                  description: Whether the user has accepted the terms.
      responses:
        '201':
          description: Returns a terms of service status object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TermsOfServiceUserStatus'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
  /terms_of_service_user_statuses/{terms_of_service_user_status_id}:
    put:
      operationId: put_terms_of_service_user_statuses_id
      summary: Update terms of service status for existing user
      tags:
        - - - - Terms of service user statuses
      x-box-tag: terms_of_service_user_statuses
      description: Updates the status for a terms of service for a user.
      parameters:
        - name: terms_of_service_user_status_id
          description: The ID of the terms of service status.
          example: '324234'
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - is_accepted
              properties:
                is_accepted:
                  type: boolean
                  example: true
                  description: Whether the user has accepted the terms.
      responses:
        '200':
          description: Returns the updated terms of service status object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TermsOfServiceUserStatus'
        default:
          description: An unexpected client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
components:
  schemas:
    TermsOfServiceUserStatuses:
      title: Terms of service user statuses
      type: object
      x-box-resource-id: terms_of_services_user_statuses
      x-box-tag: terms_of_service_user_statuses
      description: A list of terms of service user statuses
      properties:
        total_count:
          description: The total number of objects.
          example: 2
          type: integer
          format: int64
        entries:
          type: array
          description: A list of terms of service user statuses
          items:
            $ref: '#/components/schemas/TermsOfServiceUserStatus'
    ClientError:
      title: Client error
      type: object
      x-box-resource-id: client_error
      description: A generic error
      properties:
        type:
          description: error
          example: error
          type: string
          enum:
            - error
          nullable: false
        status:
          description: The HTTP status of the response.
          example: 400
          type: integer
          format: int32
          nullable: false
        code:
          description: A Box-specific error code
          example: item_name_invalid
          type: string
          enum:
            - created
            - accepted
            - no_content
            - redirect
            - not_modified
            - bad_request
            - unauthorized
            - forbidden
            - not_found
            - method_not_allowed
            - conflict
            - precondition_failed
            - too_many_requests
            - internal_server_error
            - unavailable
            - item_name_invalid
            - insufficient_scope
        message:
          description: A short message describing the error.
          example: Method Not Allowed
          type: string
          nullable: false
        context_info:
          description: |-
            A free-form object that contains additional context
            about the error. The possible fields are defined on
            a per-endpoint basis. `message` is only one example.
          type: object
          nullable: true
          properties:
            message:
              type: string
              description: More details on the error.
              example: Something went wrong.
        help_url:
          description: A URL that links to more information about why this error occurred.
          example: >-
            https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/
          type: string
          nullable: false
        request_id:
          description: |-
            A unique identifier for this response, which can be used
            when contacting Box support.
          type: string
          example: abcdef123456
          nullable: false
    TermsOfServiceUserStatus:
      title: Terms of service user status
      type: object
      x-box-resource-id: terms_of_service_user_status
      x-box-tag: terms_of_service_user_statuses
      description: The association between a Terms of Service and a user
      required:
        - id
        - type
      properties:
        id:
          type: string
          description: The unique identifier for this terms of service user status
          example: '11446498'
        type:
          type: string
          description: '`terms_of_service_user_status`'
          example: terms_of_service_user_status
          enum:
            - terms_of_service_user_status
        tos:
          allOf:
            - $ref: '#/components/schemas/TermsOfService--Base'
            - description: The terms of service
        user:
          allOf:
            - $ref: '#/components/schemas/User--Mini'
            - description: The user
        is_accepted:
          type: boolean
          example: true
          description: If the user has accepted the terms of services
        created_at:
          type: string
          format: date-time
          description: When the legal item was created
          example: '2012-12-12T10:53:43-08:00'
        modified_at:
          type: string
          format: date-time
          description: When the legal item was modified.
          example: '2012-12-12T10:53:43-08:00'
tags: []
